apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-service

  template:
    metadata:
      labels:
        app: nginx-service

    spec:
      containers:
        - name: nginx-service
          image: nginx:alpine
          #image: nginx:mainline-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080