version: '3.9'

services:

  account-service:
    build:
      context: ..
      dockerfile: account-service/Dockerfile
    container_name: account-service
    volumes:
      - ./logs:/app/logs
      - ./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar
    environment:
      OTEL_SERVICE_NAME: account-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka

  payment-service:
    build:
      context: ..
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    volumes:
      - ./logs:/app/logs
      - ./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar
    environment:
      OTEL_SERVICE_NAME: payment-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka

  fraud-service:
    build:
      context: ..
      dockerfile: fraud-service/Dockerfile
    container_name: fraud-service
    volumes:
      - ./logs:/app/logs
      - ./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar
    environment:
      OTEL_SERVICE_NAME: payment-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      # only for testing
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - account-service
      - payment-service

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"

  alloy:
    image: grafana/alloy
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ./logs:/logs
    command:
      - run
      - /etc/alloy/config.alloy
    depends_on:
      - loki

  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml
    command: "-target=all -config.file=/etc/tempo.yaml"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki

  kafka:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9094:9094"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  postgres-data: